# A magical ORM for the Nim language
#
# (c) 2026 George Lemon | MIT License
#          Made by Humans from OpenPeeps
#          https://github.com/openpeeps/ozark

import std/tables

import pkg/openparser/[sql, json]
import pkg/db_connector/[db_common, db_postgres]

import ./model

## This module implements a runtime query system that allows
## to create SQL queries from AST representations of SQL statements.


type
  RuntimeQueryBuilderPolicy* = enum
    ## An enum representing different policies for the RuntimeQueryBuilder.
    ## This can be used to control which types of SQL statements are allowed
    ## to be generated by the builder
    policyAllowNone
    policyAllowSelect
    policyAllowInsert
    policyAllowUpdate
    policyAllowDelete
    policyAllowCreate
    policyAllowDrop
    policyAllowAlter
    policyAllowTruncate
    policyAllowAllDDL           # allows all data definition statements (CREATE, DROP, ALTER, TRUNCATE) 
    policyAllowAllDML           # allows all data-modifying statements (INSERT, UPDATE, DELETE)
    policyAllowAll


  RuntimeQueryBuilder* = object
    ## A builder for constructing SQL queries from AST nodes.
    ## This is a placeholder for the actual implementation of the
    ## query builder, which would include methods for building
    ## different types of SQL statements (SELECT, INSERT, UPDATE, etc.)
    policy*: RuntimeQueryBuilderPolicy

proc createTable*(name: string, schema: OrderedTableRef[string, SqlNode]): SqlQuery =
  ## Generates a `CREATE TABLE` statement from the given
  ## table name and schema definition. The schema is a table
  ## mapping column names to their SQL definitions (as SqlNode objects).
  ## 
  ## This functions constructs an AST representing the SQL statement
  ## and then converts it to a string using the `toSql`
  ## function from the `parsesql` package.
  var stmtList = newNode(nkStmtList)
  var createTableNode = newNode(nkCreateTableIfNotExists)
  createTableNode.add(newNode(nkIdent, name))
  for colName, colDef in schema:
    createTableNode.add(colDef)
  stmtList.add(createTableNode)
  return SqlQuery($(stmtList))
